#ifndef VALUELIST
#define VALUELIST

#include "struct_deal.h"

NAME2VALUE elem_type_valuelist_array[] =
{
	{"STRING",CUBE_TYPE_STRING},
	{"UUID",CUBE_TYPE_UUID},
	{"INT",CUBE_TYPE_INT},
	{"ENUM",CUBE_TYPE_ENUM},      // an 32-bit enum
	{"FLAG",CUBE_TYPE_FLAG},
	{"TIME",CUBE_TYPE_TIME},
	{"UCHAR",CUBE_TYPE_UCHAR},
	{"USHORT",CUBE_TYPE_USHORT},   // a 16-bit unsigned word
	{"LONGLONG",CUBE_TYPE_LONGLONG}, // a 64-bit longlong integer
	{"BINDATA",CUBE_TYPE_BINDATA},  // a sequence of octets with fixed size
	{"BITMAP",CUBE_TYPE_BITMAP}, 
	{"HEXDATA",CUBE_TYPE_HEXDATA},  
	{"BINARRAY",CUBE_TYPE_BINARRAY},   
	{"UUIDARRAY",CUBE_TYPE_UUIDARRAY},   
	{"DEFUUIDARRAY",CUBE_TYPE_DEFUUIDARRAY},   
	{"DEFNAMELIST",CUBE_TYPE_DEFNAMELIST},   
	{"BOOL",CUBE_TYPE_BOOL},
	{"ESTRING",CUBE_TYPE_ESTRING},
	{"JSONSTRING",CUBE_TYPE_JSONSTRING},
	{"NODATA",CUBE_TYPE_NODATA},
	{"DEFINE",CUBE_TYPE_DEFINE},
	{"DEFSTR",CUBE_TYPE_DEFSTR},
	{"DEFSTRARRAY",CUBE_TYPE_DEFSTRARRAY},
	{"SUBSTRUCT",CUBE_TYPE_SUBSTRUCT},
        {"CHOICE",CUBE_TYPE_CHOICE},
	{"TPM64",TPM_TYPE_UINT64},
	{"TPM32",TPM_TYPE_UINT32},
	{"TPM16",TPM_TYPE_UINT16},
	{"ENDDATA",CUBE_TYPE_ENDDATA},
    	{NULL,0}
};


NAME2VALUE elem_attr_flaglist_array[] =
{
    {"INDEX",CUBE_ELEM_FLAG_INDEX},
    {"KEY",CUBE_ELEM_FLAG_KEY},
    {"DESC",CUBE_ELEM_FLAG_DESC},
    {NULL,0}
};
#endif
